spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Converts service IDs to lowercase (recommended)
      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT-SYSTEM
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /auth/$\{segment}
            - RewritePath=/users/(?<segment>.*), /users/$\{segment}

        - id: order-service
          uri: lb://ORDER-MANAGEMENT-SYSTEM
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /${segment}

server:
  port: 2029  # API Gateway port
