spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT-SYSTEM
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /auth/${segment}
            - RewritePath=/users/(?<segment>.*), /users/${segment}
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/userServiceFallback

        - id: order-service
          uri: lb://ORDER-MANAGEMENT-SYSTEM
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/orders

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - RewritePath=/notifications/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: notificationService
                fallbackUri: forward:/notificationServiceFallback

server:
  port: 2029
